### ISSUE TITLE
重新部署job丢失问题

### ISSUE THREAD

**Issue by feellmoose** [NJUPT-SAST/sast-evento-backend#100]
初步思考解决方案如下
1. quartz持久化
2. 每次存储判断时间和状态是否符合，并写回(只写回状态不加锁)
3. 脱离state只存储取消等特殊状态，其他与时间相关状态的在返回时由时间取得。

**Comment by love98ooo** [comment]
> 脱离state只存储取消等特殊状态，其他与时间相关状态的在返回时由时间取得。

这个方法需要做的修改非常多，而且每次读取event都需要根据时间计算state并不优雅
